name: Update modules

# Controls when the workflow will run
on:
  schedule:
    # Update theme automatically everyday at 00:00 UTC
    - cron: "0 0 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Update-FixIt-components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Update FixIt components
        run: git submodule update --remote --merge

      - name: Generate hugo-fixit component list
        uses: hugo-fixit/action-component-list@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment_tag_name: HUGO_FIXIT_COMPONENTS
          readme_path: README.md
          exclude_repos: 'fixit-bundle'
          template: "- [{$repo.name}]({$repo.html_url})\\\n {$repo.description}"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.repos }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ':arrow_up: Chore(FixIt): Update FixIt components'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
